# Default values for calculator-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

vars:
  namespace: calculator-web-app 
  backend:
    count_replica: 2
    service:
      port: 80
      type: ClusterIP
  frontend:
    count_replica: 1
    service:
      port: 80
      type: ClusterIP

labelsfrontend:
  type: frontend
  app.kubernetes.io/name: frontend-web

labelsbackend:
  app: backend
  env: prod

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi